In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Conexión a un archivo CSV preprocesado perteneciente a la DB MIMIC-III
# Lectura del archivo CSV en un DataFrame de Pandas
df = pd.read_csv(r'C:\Users\rocio\OneDrive\Escritorio\Cuidados_Intensivos\Modelos_Machine_Learning\modelo2.csv')

C:\Users\rocio\AppData\Local\Temp\ipykernel_20344\1460012510.py:3: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r'C:\Users\rocio\OneDrive\Escritorio\Cuidados_Intensivos\Modelos_Machine_Learning\modelo2.csv')

In [3]:
df.head()

,subject_id,fecha,Arterial BP [Systolic],Arterial Blood Pressure mean,Arterial Blood Pressure systolic,Bicarbonate,"Bilirubin, Total",Creatinine,GCS Total,Heart Rate,...,admittime,deathtime,admission_type,ethnicity,diagnosis,hospital_expire_flag,gender,dob,dod,icd9_code
0,10006,2164-09-24,NaN,NaN,NaN,27.0,NaN,7.0,NaN,NaN,...,2164-10-23 21:09:00,NaN,EMERGENCY,BLACK/AFRICAN AMERICAN,SEPSIS,0,F,2094-03-05 00:00:00,2165-08-12 00:00:00,99591
1,10006,2164-09-24,NaN,NaN,NaN,27.0,NaN,7.0,NaN,NaN,...,2164-10-23 21:09:00,NaN,EMERGENCY,BLACK/AFRICAN AMERICAN,SEPSIS,0,F,2094-03-05 00:00:00,2165-08-12 00:00:00,99662
2,10006,2164-09-24,NaN,NaN,NaN,27.0,NaN,7.0,NaN,NaN,...,2164-10-23 21:09:00,NaN,EMERGENCY,BLACK/AFRICAN AMERICAN,SEPSIS,0,F,2094-03-05 00:00:00,2165-08-12 00:00:00,5672
3,10006,2164-09-24,NaN,NaN,NaN,27.0,NaN,7.0,NaN,NaN,...,2164-10-23 21:09:00,NaN,EMERGENCY,BLACK/AFRICAN AMERICAN,SEPSIS,0,F,2094-03-05 00:00:00,2165-08-12 00:00:00,40391
4,10006,2164-09-24,NaN,NaN,NaN,27.0,NaN,7.0,NaN,NaN,...,2164-10-23 21:09:00,NaN,EMERGENCY,BLACK/AFRICAN AMERICAN,SEPSIS,0,F,2094-03-05 00:00:00,2165-08-12 00:00:00,42731

In [4]:
# # Renombra las columnas del DataFrame
# df = df.rename(columns={
#     'subject_id': 'paciente',
#     'fecha': 'fecha',
#     'Arterial BP [Systolic]': 'PAS',
#     'Arterial Blood Pressure mean': 'PAM',
#     'Arterial Blood Pressure systolic': 'sistolica',
#     'Bicarbonate': 'bicarbonato',
#     'Bilirubin, Total': 'bilirrubina',
#     'Creatinine': 'creatinina',
#     'GCS Total': 'GCS',
#     'Heart Rate': 'ritmo_cardiaco',
#     'Platelet Count': 'plaquetas',
#     'Potassium, Whole Blood': 'potasio',
#     'Whole Blood': 'sangre_total',
#     'Respiratory Rate': 'ritmo_respiratorio',
#     'Sodium, Whole Blood': 'sodio',
#     'Temperature Fahrenheit': 'temperatura_F',
#     'Urea Nitrogen': 'urea',
#     'Vancomycin/Random': 'vancomicina',
#     'WBC Count': 'glucemia',
#     'pO2': 'pO2'
# })